import type { TCoinConfig } from '../types';

export const dayTradingPreset: TCoinConfig = {
  symbol: 'DAY TRADING',
  isActive: true,
  analysisConfig: {
    candleTimeframe: '15m',
    oiWindow: 20,
    liqWindow: 20,
    liqSentWindow: 5,
    fundingWindow: 24,
    volWindow: 14,
    corrWindow: 8,
    longShortWindow: 8,
    higherMA: {
      timeframe: '4h',
      maShort: 7,
      maLong: 14,
      type: 'SMA',
      thresholdPct: 0.2,
      scale: 10,
      emaSeed: 'sma',
    },
    weights: {
      trend: 0.28,
      trendRegime: 0.17,
      liquidity: 0.18,
      funding: 0.07,
      liquidations: 0.08,
      openInterest: 0.12,
      correlation: 0.03,
      longShort: 0.03,
      higherMA: 0.04,
    },
    moduleThresholds: {
      trend: 30,
      trendRegime: 5,
      liquidity: 15,
      funding: 8,
      liquidations: 15,
      openInterest: 8,
      correlation: 8,
      longShort: 10,
      higherMA: 5,
    },
  },
  strategy: {
    entry: {
      minScore: { LONG: 40, SHORT: 40 },
      minModules: 3,
      requiredModules: ['trend'],
      maxSpreadPct: 0.05,
      cooldownMin: 10,
      avoidWhen: { volatility: 'DEAD', fundingExtreme: { absOver: 0.0008 } },
      sideBiasTolerance: 7,
    },
    volatilityFilter: { deadBelow: 0.4, extremeAbove: 2.5 },
    capital: {
      account: 100,
      riskPerTradePct: 10,
      leverage: 5,
      maxConcurrentPositions: 2,
    },
    sizing: { maxAdds: 1, addOnAdverseMovePct: 0.5, addMultiplier: 1.2 },
    exits: {
      oppositeCountExit: 0,
      tp: { use: true, tpGridPct: [2, 4, 6], tpGridSizePct: [40, 35, 25] },
      sl: {
        type: 'atr',
        hardPct: 2,
        atrMult: 1.2,
        signalRules: {
          flipIf: { scoreGap: 20, minOppScore: 60 },
          moduleFail: { required: ['trend'] },
        },
      },
      time: { maxHoldMin: 240, noPnLFallback: 'breakeven' },
      trailing: { use: true, startAfterPct: 1.0, trailStepPct: 0.5 },
    },
  },
};
