import type { TCoinConfig } from '../types';

export const scalpingPreset: TCoinConfig = {
  symbol: 'SCALPING',
  isActive: true,
  analysisConfig: {
    candleTimeframe: '1m',
    oiWindow: 13,
    liqWindow: 13,
    liqSentWindow: 5,
    fundingWindow: 15,
    volWindow: 14,
    corrWindow: 8,
    longShortWindow: 8,
    higherMA: {
      timeframe: '4h',
      maShort: 5,
      maLong: 10,
      type: 'EMA',
      thresholdPct: 0.1,
      scale: 8,
      emaSeed: 'first',
    },
    weights: {
      trend: 0.157,
      trendRegime: 0.05,
      liquidity: 0.176,
      funding: 0.0,
      liquidations: 0.157,
      openInterest: 0.44,
      correlation: 0.012,
      longShort: 0.006,
      higherMA: 0.0,
    },
    moduleThresholds: {
      trend: 15,
      trendRegime: 10,
      liquidity: 5,
      funding: 10,
      liquidations: 5,
      openInterest: 10,
      correlation: 8,
      longShort: 8,
      higherMA: 5,
    },
  },
  strategy: {
    entry: {
      minScore: { LONG: 25, SHORT: 25 },
      minModules: 2,
      requiredModules: [],
      maxSpreadPct: 0.02,
      cooldownMin: 2,
      avoidWhen: { volatility: 'DEAD', fundingExtreme: { absOver: 0.08 } },
      sideBiasTolerance: 2,
    },
    volatilityFilter: { deadBelow: 0.08, extremeAbove: 3.5 },
    capital: {
      account: 100,
      riskPerTradePct: 5,
      leverage: 10,
      maxConcurrentPositions: 2,
    },
    sizing: { maxAdds: 0, addOnAdverseMovePct: 0.3, addMultiplier: 1 },
    exits: {
      oppositeCountExit: 0,
      tp: { use: true, tpGridPct: [2, 4], tpGridSizePct: [70, 30] },
      sl: {
        type: 'hard',
        hardPct: 4,
        atrMult: 0.5,
        signalRules: {
          flipIf: { scoreGap: 15, minOppScore: 55 },
          moduleFail: { required: ['liquidity'] },
        },
      },
      time: { maxHoldMin: 5, noPnLFallback: 'closeSmallLoss' },
      trailing: { use: false, startAfterPct: 0, trailStepPct: 0 },
    },
  },
};
