import type { TCoinConfig } from '../../types';

export const dayTradingPreset: TCoinConfig = {
  symbol: 'DAY TRADING',
  isActive: true,
  analysisConfig: {
    candleTimeframe: '15m',
    oiWindow: 20,
    liqWindow: 20,
    liqSentWindow: 5,
    fundingWindow: 24,
    volWindow: 14,
    corrWindow: 8,
    longShortWindow: 8,
    higherMA: {
      timeframe: '4h',
      maShort: 7,
      maLong: 14,
      type: 'SMA',
      thresholdPct: 0.2,
      scale: 10,
      emaSeed: 'sma',
    },
    weights: {
      trend: 0.26,
      trendRegime: 0.17,
      liquidity: 0.16,
      funding: 0.1,
      liquidations: 0.08,
      openInterest: 0.12,
      correlation: 0.03,
      longShort: 0.03,
      higherMA: 0.05,
    },
    moduleThresholds: {
      trend: 25,
      trendRegime: 5,
      liquidity: 12,
      funding: 5,
      liquidations: 12,
      openInterest: 8,
      correlation: 5,
      longShort: 8,
      higherMA: 5,
    },
  },
  strategy: {
    entry: {
      minScore: { LONG: 40, SHORT: 40 },
      minModules: 3,
      requiredModules: ['trend', 'trendRegime'],
      maxSpreadPct: 0.05,
      cooldownMin: 10,
      avoidWhen: { volatility: 'DEAD', fundingExtreme: { absOver: 0.0008 } },
      sideBiasTolerance: 5,
    },
    volatilityFilter: { deadBelow: 0.4, extremeAbove: 2.5 },
    capital: {
      account: 100,
      riskPerTradePct: 8,
      leverage: 5,
      maxConcurrentPositions: 2,
    },
    sizing: { maxAdds: 1, addOnAdverseMovePct: 0.5, addMultiplier: 1.2 },
    exits: {
      oppositeCountExit: 0,
      tp: { use: true, tpGridPct: [3, 6, 9], tpGridSizePct: [50, 30, 20] },
      sl: {
        type: 'atr',
        hardPct: 5,
        atrMult: 1.8,
        signalRules: {
          flipIf: { scoreGap: 15, minOppScore: 50 },
          moduleFail: { required: ['trend', 'trendRegime'] },
        },
      },
      time: { maxHoldMin: 360, noPnLFallback: 'breakeven' },
      trailing: { use: true, startAfterPct: 1.5, trailStepPct: 0.8 },
    },
  },
};
