import type { TCoinConfig } from '../../types';

export const dayTradingPreset: TCoinConfig = {
  symbol: 'DAY TRADING',
  isActive: true,
  analysisConfig: {
    candleTimeframe: '15m',
    oiWindow: 3,
    liqWindow: 15,
    liqSentWindow: 5,
    fundingWindow: 12,
    volWindow: 14,
    corrWindow: 8,
    longShortWindow: 24,
    higherMA: {
      timeframe: '4h',
      maShort: 7,
      maLong: 14,
      type: 'SMA',
      thresholdPct: 0.2,
      scale: 10,
      emaSeed: 'sma',
    },
    weights: {
      trend: 0.26,
      trendRegime: 0.17,
      liquidity: 0.16,
      funding: 0.1,
      liquidations: 0.08,
      openInterest: 0.12,
      correlation: 0.03,
      longShort: 0.03,
      higherMA: 0.05,
      rsiVolTrend: 0,
    },
    moduleThresholds: {
      trend: 50,
      trendRegime: 55,
      liquidity: 15,
      funding: 10,
      liquidations: 15,
      openInterest: 45,
      correlation: 8,
      longShort: 25,
      higherMA: 8,
      rsiVolTrend: 0,
    },
  },
  strategy: {
    entry: {
      minScore: { LONG: 48, SHORT: 48 },
      minModules: 3,
      requiredModules: ['trend'],
      maxSpreadPct: 0.05,
      cooldownMin: 10,
      avoidWhen: { volatility: 'DEAD', fundingExtreme: { absOver: 0.0008 } },
      sideBiasTolerance: 8,
      lookback: 3,
    },
    volatilityFilter: { deadBelow: 0.3, extremeAbove: 2.2 },
    capital: {
      account: 100,
      riskPerTradePct: 7,
      leverage: 5,
      maxConcurrentPositions: 1,
    },
    sizing: { maxAdds: 0, addOnAdverseMovePct: 0.5, addMultiplier: 1.2 },
    exits: {
      oppositeCountExit: 0,
      tp: { use: true, tpGridPct: [3.5, 7, 10], tpGridSizePct: [60, 25, 15] },
      sl: {
        type: 'hard',
        hardPct: 6,
        atrMult: 1.8,
        signalRules: {
          flipIf: { scoreGap: 20, minOppScore: 55 },
          moduleFail: { required: ['trend', 'trendRegime'] },
        },
      },
      time: { maxHoldMin: 360, noPnLFallback: 'breakeven' },
      trailing: { use: true, startAfterPct: 5.0, trailStepPct: 2 },
    },
  },
};
