name: CI - Build and Test All Projects

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # Build all packages first
  build-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install all workspace dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build:packages

      - name: Verify crypto-trader-db build output
        run: |
          if [ -d "packages/crypto-trader-db/dist" ]; then
            echo "✅ Crypto Trader DB build successful - dist folder created"
            ls -la packages/crypto-trader-db/dist/
          else
            echo "❌ Crypto Trader DB build failed - dist folder not found"
            exit 1
          fi

  # Test Server Project (TypeScript)
  test-server:
    runs-on: ubuntu-latest
    needs: build-packages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - run: npm ci
      - run: npm run build --workspace=server
      - run: npx tsc --noEmit --project ./server/tsconfig.json

  # Test Console (React/TS)
  test-console:
    runs-on: ubuntu-latest
    needs: build-packages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - run: npm ci
      - run: npx tsc --noEmit --project ./crypto-trader-console/tsconfig.json
      - run: npm run lint --workspace=crypto-trader-console
      - run: npm run build --workspace=crypto-trader-console

  # Test Trader Bot
  test-trader-bot:
    runs-on: ubuntu-latest
    needs: build-packages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - run: npm ci
      - run: |
          echo "Checking syntax for all JavaScript files in trader-bot..."
          find trader-bot/src -name "*.js" -exec node --check {} \;
      - run: |
          echo "Verifying trader bot entry point..."
          node --check trader-bot/src/index.js
          echo "✅ Trader bot syntax check passed"

  # Summary
  ci-complete:
    runs-on: ubuntu-latest
    needs: [build-packages, test-server, test-console, test-trader-bot]

    steps:
      - run: |
          echo "🎉 All projects passed compilation and build checks!"
